setup.py

Bumping the version number - no review

---

README.md
agpypeline/entrypoint.py
setup.py

Changes to use correct 'species' term and fixed bug when no metadata specified
Bumped version number due to fix
Fixed code logic in entrypoint.py when no metadata specified - no processing was taking place
Updated text to reference 'species' where appropriate
Resolves agpipeline/issues-and-projects#266

Species terminology, no metadata specified fix 

---

agpypeline/geoimage.py
setup.py

Changed TIFF clipping code to accept any image larger than zero, zero.
Updated post clipping check to see if the resulting image has >zero x,y dimensions (instead of counting non-black pixels)
Updated library version number
@julianpistorius Please review
@dlebauer FYI
@jvanderleeuw Please review
Resolves agpipeline/issues-and-projects#265

Keep all black plot clipps

---

setup.py

Merging develop into main branch - no review
Will be v0.0.44 when merged

Merging develop into main branch - no review

---

.github/workflows/pylint_check.yaml

Adding ability to manually start GitHub Actions - no review

Adding manual Action start - no review

---

.github/workflows/pylint_check.yaml
agpypeline/environment.py
setup.py

Defaulting the timestamp to an empty string if it's not specified.
This is a breaking change to the way timestamps are handled by the environment.py class instance
N/A

Changing default timestamp

---

.github/workflows/pylint_check.yaml
agpypeline/environment.py
setup.py

Merging develop branch to main 
Will be v0.0.45 when merged

Merging develop to main branch - no review

---

setup.py

Changing revision number due to conflict - no review

---

.github/workflows/testing_checks.yaml

Added scheduling of Actions
Added scheduling to Actions
No review

Added schedule to Actions

---

README.md

Updated references to `main` branch name

Updated branch name to reference main

---

.github/workflows/testing_checks.yaml
README.md

Merge develop to main branch - Actions fixes

Merge develop to main branch

---

.github/workflows/testing_checks.yaml
agpypeline/entrypoint.py
agpypeline/geoimage.py
setup.py

Improved compression for images that are being compressed
Added big TIFF support for non-compressed images
Fixing the problem with saving large files
Resolves agpipeline/issues-and-projects#420

Enhanced compression

---

.github/workflows/testing_checks.yaml
agpypeline/environment.py

Fixed default timestamp when none specified - got incorrectly reverted changed in last merge
No review

Minor fixes - no review

---

.github/workflows/testing_checks.yaml
README.md
agpypeline/entrypoint.py
agpypeline/environment.py
agpypeline/geoimage.py
setup.py

Merging develop to main: create folder fix and better image compression
Will be v 0.0.48 when merged

Merging develop to main

---

.github/workflows/pypi_push_workflow.yaml
.github/workflows/testing_checks.yaml

Updating YAML branch names

---

.github/workflows/testing_checks.yaml

Removing old terraref dependency - no review

Removing old terraref dependency

---

.github/workflows/pypi_push_workflow.yaml
.github/workflows/testing_checks.yaml

Removed old dependency that was causing build issues - no review

Removed old dependency - no review

---

agpypeline/geoimage.py
agpypeline/lasfile.py
tests/test_entrypoint.py
tests/test_environment.py
tests/test_geoimage.py
tests/test_geometries.py
tests/test_lasfile.py

Fixing new pylint messages that cause Actions to fail

Fixing new pylint messages - no review

---

agpypeline/geoimage.py
agpypeline/lasfile.py
tests/test_entrypoint.py
tests/test_environment.py
tests/test_geoimage.py
tests/test_geometries.py
tests/test_lasfile.py

Merging pylint messages to main branch

Merging pylint messages to main branch - no review

---

agpypeline/geoimage.py
setup.py
tests/test_geoimage.py

Added ability to save normal tiff files (non-GeoTIFF)

added saving plain tiff - no review

---

agpypeline/geoimage.py
setup.py
tests/test_geoimage.py

Merging plain tiff saving to main branch and deploying a new version

Merging plain tiff saving to main branch

---

setup.py

Versioned setuptools

---

setup.py

Merging versioned setuptools

---

agpypeline/algorithm.py
agpypeline/environment.py
integration_tests/basic_algorithm.py
tests/test_configuration.py
tests/test_entrypoint.py

Fixing pylint action

---

.github/workflows/testing_checks.yaml
README.md
setup.py

Made changed to update the GDAL version to support Ubuntu 22.04

Update gdal version
